In [8]:
import pandas as pd
df = pd.read_excel('std_marks_sheet.xlsx')

In [19]:
df[df['python'] > 75]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
1,Muhammad Asim,10002,85,53,78,61,86,46,53,462,A
3,Hassan Raza,10004,87,99,63,64,85,43,94,535,A
4,Ali Hamza,10005,82,72,67,50,53,40,54,418,B
5,Usman Tariq,10006,91,88,62,64,80,65,49,499,A
6,Bilal Ahmed,10007,81,90,44,53,96,88,87,539,A
7,Fahad Khan,10008,93,94,99,47,54,51,41,479,A
8,Abdul Rehman,10009,93,58,51,92,62,93,66,515,A
16,Noman Ahmed,10017,81,62,94,84,54,84,67,526,A
17,Shahzaib Ali,10018,90,54,96,88,81,96,98,603,A
18,Danish Raza,10019,80,41,92,77,93,52,85,520,A
19,Waqas Ahmed,10020,81,47,82,67,41,82,52,452,A
20,Abdullah Naveed,10021,83,42,99,40,45,76,85,470,A
21,Mubashir Ali,10022,89,56,61,86,60,87,89,528,A
27,Talha Raza,10028,77,42,45,58,82,43,61,408,B
29,Sameer Ahmed,10030,91,75,82,72,56,67,91,534,A
32,Junaid Ahmed,10033,80,73,76,95,83,93,43,543,A
33,Zubair Ali,10034,77,98,60,42,100,100,62,539,A
34,Irfan Ahmed,10035,94,66,85,87,64,65,76,537,A
35,Kashif Raza,10036,80,65,48,83,82,91,69,518,A
36,Nouman Ali,10037,81,48,70,78,97,52,53,479,A
37,Owais Ahmed,10038,95,56,50,59,62,85,76,483,A
39,Huzaifa Ali,10040,78,95,53,71,62,75,50,484,A
43,Farhan Ahmed,10044,94,87,43,62,50,94,71,501,A
44,Ubaid Raza,10045,83,56,69,83,67,48,89,495,A
50,Shahmeer Raza,10051,92,88,44,80,63,45,56,468,A
51,Zahid Ali,10052,78,44,60,93,98,61,73,507,A
52,Qasim Ahmed,10053,95,60,44,70,97,93,76,535,A
53,Muneeb Raza,10054,97,93,83,46,60,65,68,512,A
57,Khalid Ali,10058,86,85,97,48,74,55,46,491,A
63,Ibrahim Ali,10064,91,58,56,100,98,49,93,545,A
64,Azlan Ahmed,10065,83,81,49,42,40,79,59,433,B
67,Naveed Ahmed,10068,90,80,59,76,55,54,66,480,A
68,Jibran Raza,10069,85,49,58,55,84,77,60,468,A
70,Saif Ahmed,10071,85,59,76,68,77,50,72,487,A
71,Rafay Raza,10072,90,43,97,50,88,81,75,524,A
72,Ehsan Ali,10073,83,77,47,80,71,79,77,514,A
74,Zarar Raza,10075,87,48,66,88,74,98,44,505,A
76,Ismail Ahmed,10077,79,85,84,97,78,92,62,577,A
80,Rizwan Ahmed,10081,85,40,74,96,84,93,40,512,A
81,Shakir Raza,10082,99,95,77,47,84,98,58,558,A
83,Amin Ahmed,10084,100,95,92,85,89,87,48,596,A
87,Zayan Raza,10088,97,75,44,80,74,60,41,471,A
88,Akram Ali,10089,76,55,42,54,49,47,91,414,B
91,Rohail Raza,10092,83,78,70,65,70,65,82,513,A
92,Shahbaz Ahmed,10093,82,75,68,74,83,57,65,504,A
98,Nabeel Ahmed,10099,97,75,81,98,72,50,85,558,A
99,Dawood Raza,10100,82,62,42,80,54,49,43,412,B

In [20]:
df[df['Grade'] == 'A']

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
1,Muhammad Asim,10002,85,53,78,61,86,46,53,462,A
2,Asad Ali,10003,60,97,73,57,52,80,50,469,A
3,Hassan Raza,10004,87,99,63,64,85,43,94,535,A
5,Usman Tariq,10006,91,88,62,64,80,65,49,499,A
6,Bilal Ahmed,10007,81,90,44,53,96,88,87,539,A
...,...,...,...,...,...,...,...,...,...,...,...
94,Affan Raza,10095,72,48,99,57,73,76,81,506,A
95,Hasnain Ahmed,10096,62,100,85,54,96,94,83,574,A
96,Zubair Raza,10097,42,60,88,92,57,56,59,454,A
97,Ahmer Ali,10098,45,60,60,91,60,57,98,471,A
98,Nabeel Ahmed,10099,97,75,81,98,72,50,85,558,A

In [21]:
df[df['numpy'] < 60]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
1,Muhammad Asim,10002,85,53,78,61,86,46,53,462,A
8,Abdul Rehman,10009,93,58,51,92,62,93,66,515,A
15,Imran Khan,10016,51,42,74,53,57,51,83,411,B
17,Shahzaib Ali,10018,90,54,96,88,81,96,98,603,A
18,Danish Raza,10019,80,41,92,77,93,52,85,520,A
19,Waqas Ahmed,10020,81,47,82,67,41,82,52,452,A
20,Abdullah Naveed,10021,83,42,99,40,45,76,85,470,A
21,Mubashir Ali,10022,89,56,61,86,60,87,89,528,A
22,Taha Raza,10023,42,56,88,63,95,76,75,495,A
25,Rizwan Ali,10026,66,48,99,74,81,81,97,546,A
27,Talha Raza,10028,77,42,45,58,82,43,61,408,B
28,Faizan Khan,10029,62,40,92,99,47,63,71,474,A
36,Nouman Ali,10037,81,48,70,78,97,52,53,479,A
37,Owais Ahmed,10038,95,56,50,59,62,85,76,483,A
44,Ubaid Raza,10045,83,56,69,83,67,48,89,495,A
45,Shayan Ali,10046,67,50,90,70,82,41,43,443,B
46,Ammar Ahmed,10047,48,50,40,62,87,93,96,476,A
51,Zahid Ali,10052,78,44,60,93,98,61,73,507,A
61,Murtaza Ahmed,10062,73,41,89,85,74,41,46,449,B
63,Ibrahim Ali,10064,91,58,56,100,98,49,93,545,A
65,Awais Raza,10066,54,50,62,68,73,77,62,446,B
68,Jibran Raza,10069,85,49,58,55,84,77,60,468,A
69,Abrar Ali,10070,66,44,49,69,55,65,54,402,B
70,Saif Ahmed,10071,85,59,76,68,77,50,72,487,A
71,Rafay Raza,10072,90,43,97,50,88,81,75,524,A
73,Shahid Ahmed,10074,62,46,61,68,42,47,64,390,B
74,Zarar Raza,10075,87,48,66,88,74,98,44,505,A
75,Rameez Ali,10076,62,46,73,58,49,88,94,470,A
80,Rizwan Ahmed,10081,85,40,74,96,84,93,40,512,A
85,Atif Ali,10086,57,54,83,42,68,52,98,454,A
88,Akram Ali,10089,76,55,42,54,49,47,91,414,B
94,Affan Raza,10095,72,48,99,57,73,76,81,506,A

In [22]:
df[df['Total'] > 450]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
1,Muhammad Asim,10002,85,53,78,61,86,46,53,462,A
2,Asad Ali,10003,60,97,73,57,52,80,50,469,A
3,Hassan Raza,10004,87,99,63,64,85,43,94,535,A
5,Usman Tariq,10006,91,88,62,64,80,65,49,499,A
6,Bilal Ahmed,10007,81,90,44,53,96,88,87,539,A
...,...,...,...,...,...,...,...,...,...,...,...
94,Affan Raza,10095,72,48,99,57,73,76,81,506,A
95,Hasnain Ahmed,10096,62,100,85,54,96,94,83,574,A
96,Zubair Raza,10097,42,60,88,92,57,56,59,454,A
97,Ahmer Ali,10098,45,60,60,91,60,57,98,471,A
98,Nabeel Ahmed,10099,97,75,81,98,72,50,85,558,A

In [23]:
df[df['pandas'] > 80][['name', 'roll num']]

               name  roll num
7        Fahad Khan     10008
11       Saad Ahmed     10012
12      Umer Farooq     10013
16      Noman Ahmed     10017
17     Shahzaib Ali     10018
18      Danish Raza     10019
19      Waqas Ahmed     10020
20  Abdullah Naveed     10021
22        Taha Raza     10023
25       Rizwan Ali     10026
28      Faizan Khan     10029
29     Sameer Ahmed     10030
31       Yasir Raza     10032
34      Irfan Ahmed     10035
40       Anas Ahmed     10041
41       Rayan Raza     10042
45       Shayan Ali     10046
47     Zeeshan Raza     10048
53      Muneeb Raza     10054
57       Khalid Ali     10058
61    Murtaza Ahmed     10062
62      Furqan Raza     10063
71       Rafay Raza     10072
76     Ismail Ahmed     10077
77       Ahsan Raza     10078
82       Faisal Ali     10083
83       Amin Ahmed     10084
85         Atif Ali     10086
94       Affan Raza     10095
95    Hasnain Ahmed     10096
96      Zubair Raza     10097
98     Nabeel Ahmed     10099

In [24]:
df[df['streamlit'].between(60, 80)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
0,Ahmed Raza,10001,52,64,52,74,51,49,70,412,B
1,Muhammad Asim,10002,85,53,78,61,86,46,53,462,A
3,Hassan Raza,10004,87,99,63,64,85,43,94,535,A
5,Usman Tariq,10006,91,88,62,64,80,65,49,499,A
13,Salman Raza,10014,49,83,56,61,63,91,54,457,A
18,Danish Raza,10019,80,41,92,77,93,52,85,520,A
19,Waqas Ahmed,10020,81,47,82,67,41,82,52,452,A
22,Taha Raza,10023,42,56,88,63,95,76,75,495,A
24,Shoaib Malik,10025,72,82,72,68,98,55,73,520,A
25,Rizwan Ali,10026,66,48,99,74,81,81,97,546,A
29,Sameer Ahmed,10030,91,75,82,72,56,67,91,534,A
36,Nouman Ali,10037,81,48,70,78,97,52,53,479,A
38,Moiz Raza,10039,42,81,77,69,97,79,92,537,A
39,Huzaifa Ali,10040,78,95,53,71,62,75,50,484,A
40,Anas Ahmed,10041,60,69,90,66,93,85,79,542,A
42,Adnan Ali,10043,44,89,58,70,49,60,72,442,B
43,Farhan Ahmed,10044,94,87,43,62,50,94,71,501,A
45,Shayan Ali,10046,67,50,90,70,82,41,43,443,B
46,Ammar Ahmed,10047,48,50,40,62,87,93,96,476,A
47,Zeeshan Raza,10048,41,74,87,60,91,96,61,510,A
48,Rehan Ali,10049,42,87,48,76,86,74,83,496,A
49,Mustafa Ahmed,10050,41,82,43,64,79,100,76,485,A
50,Shahmeer Raza,10051,92,88,44,80,63,45,56,468,A
52,Qasim Ahmed,10053,95,60,44,70,97,93,76,535,A
54,Ayaan Ali,10055,50,70,70,72,49,91,43,445,B
55,Areeb Ahmed,10056,75,93,80,63,58,70,87,526,A
59,Basit Raza,10060,46,97,56,78,56,89,65,487,A
65,Awais Raza,10066,54,50,62,68,73,77,62,446,B
66,Sufyan Ali,10067,74,83,72,67,66,99,56,517,A
67,Naveed Ahmed,10068,90,80,59,76,55,54,66,480,A
69,Abrar Ali,10070,66,44,49,69,55,65,54,402,B
70,Saif Ahmed,10071,85,59,76,68,77,50,72,487,A
72,Ehsan Ali,10073,83,77,47,80,71,79,77,514,A
73,Shahid Ahmed,10074,62,46,61,68,42,47,64,390,B
77,Ahsan Raza,10078,43,88,91,78,62,81,62,505,A
79,Hammad Ali,10080,49,67,79,68,50,51,93,457,A
87,Zayan Raza,10088,97,75,44,80,74,60,41,471,A
91,Rohail Raza,10092,83,78,70,65,70,65,82,513,A
92,Shahbaz Ahmed,10093,82,75,68,74,83,57,65,504,A
93,Taimoor Ali,10094,60,69,44,72,94,46,56,441,B
99,Dawood Raza,10100,82,62,42,80,54,49,43,412,B

In [25]:
df[df['ML'] == 90]

Empty DataFrame
Columns: [name, roll num, python, numpy, pandas, streamlit, ML, DL, NLP, Total, Grade]
Index: []

In [26]:
df[df['DL'] < 50]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
0,Ahmed Raza,10001,52,64,52,74,51,49,70,412,B
1,Muhammad Asim,10002,85,53,78,61,86,46,53,462,A
3,Hassan Raza,10004,87,99,63,64,85,43,94,535,A
4,Ali Hamza,10005,82,72,67,50,53,40,54,418,B
10,Ahsan Iqbal,10011,48,87,76,45,83,41,55,435,B
26,Adeel Ahmed,10027,59,86,80,57,59,41,85,467,A
27,Talha Raza,10028,77,42,45,58,82,43,61,408,B
44,Ubaid Raza,10045,83,56,69,83,67,48,89,495,A
45,Shayan Ali,10046,67,50,90,70,82,41,43,443,B
50,Shahmeer Raza,10051,92,88,44,80,63,45,56,468,A
61,Murtaza Ahmed,10062,73,41,89,85,74,41,46,449,B
62,Furqan Raza,10063,60,76,99,54,61,43,93,486,A
63,Ibrahim Ali,10064,91,58,56,100,98,49,93,545,A
73,Shahid Ahmed,10074,62,46,61,68,42,47,64,390,B
88,Akram Ali,10089,76,55,42,54,49,47,91,414,B
93,Taimoor Ali,10094,60,69,44,72,94,46,56,441,B
99,Dawood Raza,10100,82,62,42,80,54,49,43,412,B

In [27]:
df[df['NLP'] > 65]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
0,Ahmed Raza,10001,52,64,52,74,51,49,70,412,B
3,Hassan Raza,10004,87,99,63,64,85,43,94,535,A
6,Bilal Ahmed,10007,81,90,44,53,96,88,87,539,A
8,Abdul Rehman,10009,93,58,51,92,62,93,66,515,A
9,Zain Ali,10010,71,100,71,93,73,88,85,581,A
11,Saad Ahmed,10012,75,100,99,48,80,60,76,538,A
12,Umer Farooq,10013,47,89,98,42,48,85,95,504,A
14,Hamza Ali,10015,45,73,45,95,67,75,95,495,A
15,Imran Khan,10016,51,42,74,53,57,51,83,411,B
16,Noman Ahmed,10017,81,62,94,84,54,84,67,526,A
17,Shahzaib Ali,10018,90,54,96,88,81,96,98,603,A
18,Danish Raza,10019,80,41,92,77,93,52,85,520,A
20,Abdullah Naveed,10021,83,42,99,40,45,76,85,470,A
21,Mubashir Ali,10022,89,56,61,86,60,87,89,528,A
22,Taha Raza,10023,42,56,88,63,95,76,75,495,A
23,Arslan Ahmed,10024,52,83,44,94,57,55,90,475,A
24,Shoaib Malik,10025,72,82,72,68,98,55,73,520,A
25,Rizwan Ali,10026,66,48,99,74,81,81,97,546,A
26,Adeel Ahmed,10027,59,86,80,57,59,41,85,467,A
28,Faizan Khan,10029,62,40,92,99,47,63,71,474,A
29,Sameer Ahmed,10030,91,75,82,72,56,67,91,534,A
30,Haris Ali,10031,54,95,79,85,78,60,98,549,A
31,Yasir Raza,10032,56,75,96,52,76,99,79,533,A
34,Irfan Ahmed,10035,94,66,85,87,64,65,76,537,A
35,Kashif Raza,10036,80,65,48,83,82,91,69,518,A
37,Owais Ahmed,10038,95,56,50,59,62,85,76,483,A
38,Moiz Raza,10039,42,81,77,69,97,79,92,537,A
40,Anas Ahmed,10041,60,69,90,66,93,85,79,542,A
41,Rayan Raza,10042,67,94,82,46,49,64,95,497,A
42,Adnan Ali,10043,44,89,58,70,49,60,72,442,B
43,Farhan Ahmed,10044,94,87,43,62,50,94,71,501,A
44,Ubaid Raza,10045,83,56,69,83,67,48,89,495,A
46,Ammar Ahmed,10047,48,50,40,62,87,93,96,476,A
48,Rehan Ali,10049,42,87,48,76,86,74,83,496,A
49,Mustafa Ahmed,10050,41,82,43,64,79,100,76,485,A
51,Zahid Ali,10052,78,44,60,93,98,61,73,507,A
52,Qasim Ahmed,10053,95,60,44,70,97,93,76,535,A
53,Muneeb Raza,10054,97,93,83,46,60,65,68,512,A
55,Areeb Ahmed,10056,75,93,80,63,58,70,87,526,A
56,Sami Raza,10057,67,97,68,40,69,60,67,468,A
62,Furqan Raza,10063,60,76,99,54,61,43,93,486,A
63,Ibrahim Ali,10064,91,58,56,100,98,49,93,545,A
67,Naveed Ahmed,10068,90,80,59,76,55,54,66,480,A
70,Saif Ahmed,10071,85,59,76,68,77,50,72,487,A
71,Rafay Raza,10072,90,43,97,50,88,81,75,524,A
72,Ehsan Ali,10073,83,77,47,80,71,79,77,514,A
75,Rameez Ali,10076,62,46,73,58,49,88,94,470,A
78,Zain Ul Abidin,10079,56,61,71,90,65,66,92,501,A
79,Hammad Ali,10080,49,67,79,68,50,51,93,457,A
85,Atif Ali,10086,57,54,83,42,68,52,98,454,A
86,Waqar Ahmed,10087,48,72,43,59,67,85,70,444,B
88,Akram Ali,10089,76,55,42,54,49,47,91,414,B
89,Haseeb Ahmed,10090,56,71,63,88,59,78,99,514,A
90,Mahad Ali,10091,44,80,62,53,83,76,97,495,A
91,Rohail Raza,10092,83,78,70,65,70,65,82,513,A
94,Affan Raza,10095,72,48,99,57,73,76,81,506,A
95,Hasnain Ahmed,10096,62,100,85,54,96,94,83,574,A
97,Ahmer Ali,10098,45,60,60,91,60,57,98,471,A
98,Nabeel Ahmed,10099,97,75,81,98,72,50,85,558,A

In [28]:
df[df['Total'] < 400]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
73,Shahid Ahmed,10074,62,46,61,68,42,47,64,390,B

In [29]:
df[(df['python'] > 70) & (df['numpy'] > 70)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
3,Hassan Raza,10004,87,99,63,64,85,43,94,535,A
4,Ali Hamza,10005,82,72,67,50,53,40,54,418,B
5,Usman Tariq,10006,91,88,62,64,80,65,49,499,A
6,Bilal Ahmed,10007,81,90,44,53,96,88,87,539,A
7,Fahad Khan,10008,93,94,99,47,54,51,41,479,A
9,Zain Ali,10010,71,100,71,93,73,88,85,581,A
11,Saad Ahmed,10012,75,100,99,48,80,60,76,538,A
24,Shoaib Malik,10025,72,82,72,68,98,55,73,520,A
29,Sameer Ahmed,10030,91,75,82,72,56,67,91,534,A
32,Junaid Ahmed,10033,80,73,76,95,83,93,43,543,A
33,Zubair Ali,10034,77,98,60,42,100,100,62,539,A
39,Huzaifa Ali,10040,78,95,53,71,62,75,50,484,A
43,Farhan Ahmed,10044,94,87,43,62,50,94,71,501,A
50,Shahmeer Raza,10051,92,88,44,80,63,45,56,468,A
53,Muneeb Raza,10054,97,93,83,46,60,65,68,512,A
55,Areeb Ahmed,10056,75,93,80,63,58,70,87,526,A
57,Khalid Ali,10058,86,85,97,48,74,55,46,491,A
64,Azlan Ahmed,10065,83,81,49,42,40,79,59,433,B
66,Sufyan Ali,10067,74,83,72,67,66,99,56,517,A
67,Naveed Ahmed,10068,90,80,59,76,55,54,66,480,A
72,Ehsan Ali,10073,83,77,47,80,71,79,77,514,A
76,Ismail Ahmed,10077,79,85,84,97,78,92,62,577,A
81,Shakir Raza,10082,99,95,77,47,84,98,58,558,A
83,Amin Ahmed,10084,100,95,92,85,89,87,48,596,A
87,Zayan Raza,10088,97,75,44,80,74,60,41,471,A
91,Rohail Raza,10092,83,78,70,65,70,65,82,513,A
92,Shahbaz Ahmed,10093,82,75,68,74,83,57,65,504,A
98,Nabeel Ahmed,10099,97,75,81,98,72,50,85,558,A

In [30]:
df[df['pandas'] < 60]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
0,Ahmed Raza,10001,52,64,52,74,51,49,70,412,B
6,Bilal Ahmed,10007,81,90,44,53,96,88,87,539,A
8,Abdul Rehman,10009,93,58,51,92,62,93,66,515,A
13,Salman Raza,10014,49,83,56,61,63,91,54,457,A
14,Hamza Ali,10015,45,73,45,95,67,75,95,495,A
23,Arslan Ahmed,10024,52,83,44,94,57,55,90,475,A
27,Talha Raza,10028,77,42,45,58,82,43,61,408,B
35,Kashif Raza,10036,80,65,48,83,82,91,69,518,A
37,Owais Ahmed,10038,95,56,50,59,62,85,76,483,A
39,Huzaifa Ali,10040,78,95,53,71,62,75,50,484,A
42,Adnan Ali,10043,44,89,58,70,49,60,72,442,B
43,Farhan Ahmed,10044,94,87,43,62,50,94,71,501,A
46,Ammar Ahmed,10047,48,50,40,62,87,93,96,476,A
48,Rehan Ali,10049,42,87,48,76,86,74,83,496,A
49,Mustafa Ahmed,10050,41,82,43,64,79,100,76,485,A
50,Shahmeer Raza,10051,92,88,44,80,63,45,56,468,A
52,Qasim Ahmed,10053,95,60,44,70,97,93,76,535,A
58,Afaq Ahmed,10059,51,70,45,94,72,81,40,453,A
59,Basit Raza,10060,46,97,56,78,56,89,65,487,A
63,Ibrahim Ali,10064,91,58,56,100,98,49,93,545,A
64,Azlan Ahmed,10065,83,81,49,42,40,79,59,433,B
67,Naveed Ahmed,10068,90,80,59,76,55,54,66,480,A
68,Jibran Raza,10069,85,49,58,55,84,77,60,468,A
69,Abrar Ali,10070,66,44,49,69,55,65,54,402,B
72,Ehsan Ali,10073,83,77,47,80,71,79,77,514,A
86,Waqar Ahmed,10087,48,72,43,59,67,85,70,444,B
87,Zayan Raza,10088,97,75,44,80,74,60,41,471,A
88,Akram Ali,10089,76,55,42,54,49,47,91,414,B
93,Taimoor Ali,10094,60,69,44,72,94,46,56,441,B
99,Dawood Raza,10100,82,62,42,80,54,49,43,412,B

In [31]:
df[df['Grade'] == 'B']

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
0,Ahmed Raza,10001,52,64,52,74,51,49,70,412,B
4,Ali Hamza,10005,82,72,67,50,53,40,54,418,B
10,Ahsan Iqbal,10011,48,87,76,45,83,41,55,435,B
15,Imran Khan,10016,51,42,74,53,57,51,83,411,B
27,Talha Raza,10028,77,42,45,58,82,43,61,408,B
42,Adnan Ali,10043,44,89,58,70,49,60,72,442,B
45,Shayan Ali,10046,67,50,90,70,82,41,43,443,B
54,Ayaan Ali,10055,50,70,70,72,49,91,43,445,B
60,Kamran Ali,10061,59,69,66,47,88,61,41,431,B
61,Murtaza Ahmed,10062,73,41,89,85,74,41,46,449,B
64,Azlan Ahmed,10065,83,81,49,42,40,79,59,433,B
65,Awais Raza,10066,54,50,62,68,73,77,62,446,B
69,Abrar Ali,10070,66,44,49,69,55,65,54,402,B
73,Shahid Ahmed,10074,62,46,61,68,42,47,64,390,B
86,Waqar Ahmed,10087,48,72,43,59,67,85,70,444,B
88,Akram Ali,10089,76,55,42,54,49,47,91,414,B
93,Taimoor Ali,10094,60,69,44,72,94,46,56,441,B
99,Dawood Raza,10100,82,62,42,80,54,49,43,412,B

In [32]:
df[df['ML'] > 85]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
1,Muhammad Asim,10002,85,53,78,61,86,46,53,462,A
6,Bilal Ahmed,10007,81,90,44,53,96,88,87,539,A
18,Danish Raza,10019,80,41,92,77,93,52,85,520,A
22,Taha Raza,10023,42,56,88,63,95,76,75,495,A
24,Shoaib Malik,10025,72,82,72,68,98,55,73,520,A
33,Zubair Ali,10034,77,98,60,42,100,100,62,539,A
36,Nouman Ali,10037,81,48,70,78,97,52,53,479,A
38,Moiz Raza,10039,42,81,77,69,97,79,92,537,A
40,Anas Ahmed,10041,60,69,90,66,93,85,79,542,A
46,Ammar Ahmed,10047,48,50,40,62,87,93,96,476,A
47,Zeeshan Raza,10048,41,74,87,60,91,96,61,510,A
48,Rehan Ali,10049,42,87,48,76,86,74,83,496,A
51,Zahid Ali,10052,78,44,60,93,98,61,73,507,A
52,Qasim Ahmed,10053,95,60,44,70,97,93,76,535,A
60,Kamran Ali,10061,59,69,66,47,88,61,41,431,B
63,Ibrahim Ali,10064,91,58,56,100,98,49,93,545,A
71,Rafay Raza,10072,90,43,97,50,88,81,75,524,A
83,Amin Ahmed,10084,100,95,92,85,89,87,48,596,A
93,Taimoor Ali,10094,60,69,44,72,94,46,56,441,B
95,Hasnain Ahmed,10096,62,100,85,54,96,94,83,574,A

In [33]:
df[df['streamlit'] < 55]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
4,Ali Hamza,10005,82,72,67,50,53,40,54,418,B
6,Bilal Ahmed,10007,81,90,44,53,96,88,87,539,A
7,Fahad Khan,10008,93,94,99,47,54,51,41,479,A
10,Ahsan Iqbal,10011,48,87,76,45,83,41,55,435,B
11,Saad Ahmed,10012,75,100,99,48,80,60,76,538,A
12,Umer Farooq,10013,47,89,98,42,48,85,95,504,A
15,Imran Khan,10016,51,42,74,53,57,51,83,411,B
20,Abdullah Naveed,10021,83,42,99,40,45,76,85,470,A
31,Yasir Raza,10032,56,75,96,52,76,99,79,533,A
33,Zubair Ali,10034,77,98,60,42,100,100,62,539,A
41,Rayan Raza,10042,67,94,82,46,49,64,95,497,A
53,Muneeb Raza,10054,97,93,83,46,60,65,68,512,A
56,Sami Raza,10057,67,97,68,40,69,60,67,468,A
57,Khalid Ali,10058,86,85,97,48,74,55,46,491,A
60,Kamran Ali,10061,59,69,66,47,88,61,41,431,B
62,Furqan Raza,10063,60,76,99,54,61,43,93,486,A
64,Azlan Ahmed,10065,83,81,49,42,40,79,59,433,B
71,Rafay Raza,10072,90,43,97,50,88,81,75,524,A
81,Shakir Raza,10082,99,95,77,47,84,98,58,558,A
82,Faisal Ali,10083,53,77,99,42,77,84,64,496,A
85,Atif Ali,10086,57,54,83,42,68,52,98,454,A
88,Akram Ali,10089,76,55,42,54,49,47,91,414,B
90,Mahad Ali,10091,44,80,62,53,83,76,97,495,A
95,Hasnain Ahmed,10096,62,100,85,54,96,94,83,574,A

In [34]:
df[df['python'].between(60, 90)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
1,Muhammad Asim,10002,85,53,78,61,86,46,53,462,A
2,Asad Ali,10003,60,97,73,57,52,80,50,469,A
3,Hassan Raza,10004,87,99,63,64,85,43,94,535,A
4,Ali Hamza,10005,82,72,67,50,53,40,54,418,B
6,Bilal Ahmed,10007,81,90,44,53,96,88,87,539,A
9,Zain Ali,10010,71,100,71,93,73,88,85,581,A
11,Saad Ahmed,10012,75,100,99,48,80,60,76,538,A
16,Noman Ahmed,10017,81,62,94,84,54,84,67,526,A
17,Shahzaib Ali,10018,90,54,96,88,81,96,98,603,A
18,Danish Raza,10019,80,41,92,77,93,52,85,520,A
19,Waqas Ahmed,10020,81,47,82,67,41,82,52,452,A
20,Abdullah Naveed,10021,83,42,99,40,45,76,85,470,A
21,Mubashir Ali,10022,89,56,61,86,60,87,89,528,A
24,Shoaib Malik,10025,72,82,72,68,98,55,73,520,A
25,Rizwan Ali,10026,66,48,99,74,81,81,97,546,A
27,Talha Raza,10028,77,42,45,58,82,43,61,408,B
28,Faizan Khan,10029,62,40,92,99,47,63,71,474,A
32,Junaid Ahmed,10033,80,73,76,95,83,93,43,543,A
33,Zubair Ali,10034,77,98,60,42,100,100,62,539,A
35,Kashif Raza,10036,80,65,48,83,82,91,69,518,A
36,Nouman Ali,10037,81,48,70,78,97,52,53,479,A
39,Huzaifa Ali,10040,78,95,53,71,62,75,50,484,A
40,Anas Ahmed,10041,60,69,90,66,93,85,79,542,A
41,Rayan Raza,10042,67,94,82,46,49,64,95,497,A
44,Ubaid Raza,10045,83,56,69,83,67,48,89,495,A
45,Shayan Ali,10046,67,50,90,70,82,41,43,443,B
51,Zahid Ali,10052,78,44,60,93,98,61,73,507,A
55,Areeb Ahmed,10056,75,93,80,63,58,70,87,526,A
56,Sami Raza,10057,67,97,68,40,69,60,67,468,A
57,Khalid Ali,10058,86,85,97,48,74,55,46,491,A
61,Murtaza Ahmed,10062,73,41,89,85,74,41,46,449,B
62,Furqan Raza,10063,60,76,99,54,61,43,93,486,A
64,Azlan Ahmed,10065,83,81,49,42,40,79,59,433,B
66,Sufyan Ali,10067,74,83,72,67,66,99,56,517,A
67,Naveed Ahmed,10068,90,80,59,76,55,54,66,480,A
68,Jibran Raza,10069,85,49,58,55,84,77,60,468,A
69,Abrar Ali,10070,66,44,49,69,55,65,54,402,B
70,Saif Ahmed,10071,85,59,76,68,77,50,72,487,A
71,Rafay Raza,10072,90,43,97,50,88,81,75,524,A
72,Ehsan Ali,10073,83,77,47,80,71,79,77,514,A
73,Shahid Ahmed,10074,62,46,61,68,42,47,64,390,B
74,Zarar Raza,10075,87,48,66,88,74,98,44,505,A
75,Rameez Ali,10076,62,46,73,58,49,88,94,470,A
76,Ismail Ahmed,10077,79,85,84,97,78,92,62,577,A
80,Rizwan Ahmed,10081,85,40,74,96,84,93,40,512,A
84,Sarmad Raza,10085,73,69,67,95,41,51,65,461,A
88,Akram Ali,10089,76,55,42,54,49,47,91,414,B
91,Rohail Raza,10092,83,78,70,65,70,65,82,513,A
92,Shahbaz Ahmed,10093,82,75,68,74,83,57,65,504,A
93,Taimoor Ali,10094,60,69,44,72,94,46,56,441,B
94,Affan Raza,10095,72,48,99,57,73,76,81,506,A
95,Hasnain Ahmed,10096,62,100,85,54,96,94,83,574,A
99,Dawood Raza,10100,82,62,42,80,54,49,43,412,B

In [35]:
df[(df['pandas'] > 70) & (df['NLP'] > 70)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
9,Zain Ali,10010,71,100,71,93,73,88,85,581,A
11,Saad Ahmed,10012,75,100,99,48,80,60,76,538,A
12,Umer Farooq,10013,47,89,98,42,48,85,95,504,A
15,Imran Khan,10016,51,42,74,53,57,51,83,411,B
17,Shahzaib Ali,10018,90,54,96,88,81,96,98,603,A
18,Danish Raza,10019,80,41,92,77,93,52,85,520,A
20,Abdullah Naveed,10021,83,42,99,40,45,76,85,470,A
22,Taha Raza,10023,42,56,88,63,95,76,75,495,A
24,Shoaib Malik,10025,72,82,72,68,98,55,73,520,A
25,Rizwan Ali,10026,66,48,99,74,81,81,97,546,A
26,Adeel Ahmed,10027,59,86,80,57,59,41,85,467,A
28,Faizan Khan,10029,62,40,92,99,47,63,71,474,A
29,Sameer Ahmed,10030,91,75,82,72,56,67,91,534,A
30,Haris Ali,10031,54,95,79,85,78,60,98,549,A
31,Yasir Raza,10032,56,75,96,52,76,99,79,533,A
34,Irfan Ahmed,10035,94,66,85,87,64,65,76,537,A
38,Moiz Raza,10039,42,81,77,69,97,79,92,537,A
40,Anas Ahmed,10041,60,69,90,66,93,85,79,542,A
41,Rayan Raza,10042,67,94,82,46,49,64,95,497,A
55,Areeb Ahmed,10056,75,93,80,63,58,70,87,526,A
62,Furqan Raza,10063,60,76,99,54,61,43,93,486,A
70,Saif Ahmed,10071,85,59,76,68,77,50,72,487,A
71,Rafay Raza,10072,90,43,97,50,88,81,75,524,A
75,Rameez Ali,10076,62,46,73,58,49,88,94,470,A
78,Zain Ul Abidin,10079,56,61,71,90,65,66,92,501,A
79,Hammad Ali,10080,49,67,79,68,50,51,93,457,A
85,Atif Ali,10086,57,54,83,42,68,52,98,454,A
94,Affan Raza,10095,72,48,99,57,73,76,81,506,A
95,Hasnain Ahmed,10096,62,100,85,54,96,94,83,574,A
98,Nabeel Ahmed,10099,97,75,81,98,72,50,85,558,A

In [36]:
df[df['DL'] > 60]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
2,Asad Ali,10003,60,97,73,57,52,80,50,469,A
5,Usman Tariq,10006,91,88,62,64,80,65,49,499,A
6,Bilal Ahmed,10007,81,90,44,53,96,88,87,539,A
8,Abdul Rehman,10009,93,58,51,92,62,93,66,515,A
9,Zain Ali,10010,71,100,71,93,73,88,85,581,A
...,...,...,...,...,...,...,...,...,...,...,...
89,Haseeb Ahmed,10090,56,71,63,88,59,78,99,514,A
90,Mahad Ali,10091,44,80,62,53,83,76,97,495,A
91,Rohail Raza,10092,83,78,70,65,70,65,82,513,A
94,Affan Raza,10095,72,48,99,57,73,76,81,506,A
95,Hasnain Ahmed,10096,62,100,85,54,96,94,83,574,A

In [37]:
df[df['Total'].between(400, 500)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
0,Ahmed Raza,10001,52,64,52,74,51,49,70,412,B
1,Muhammad Asim,10002,85,53,78,61,86,46,53,462,A
2,Asad Ali,10003,60,97,73,57,52,80,50,469,A
4,Ali Hamza,10005,82,72,67,50,53,40,54,418,B
5,Usman Tariq,10006,91,88,62,64,80,65,49,499,A
7,Fahad Khan,10008,93,94,99,47,54,51,41,479,A
10,Ahsan Iqbal,10011,48,87,76,45,83,41,55,435,B
13,Salman Raza,10014,49,83,56,61,63,91,54,457,A
14,Hamza Ali,10015,45,73,45,95,67,75,95,495,A
15,Imran Khan,10016,51,42,74,53,57,51,83,411,B
19,Waqas Ahmed,10020,81,47,82,67,41,82,52,452,A
20,Abdullah Naveed,10021,83,42,99,40,45,76,85,470,A
22,Taha Raza,10023,42,56,88,63,95,76,75,495,A
23,Arslan Ahmed,10024,52,83,44,94,57,55,90,475,A
26,Adeel Ahmed,10027,59,86,80,57,59,41,85,467,A
27,Talha Raza,10028,77,42,45,58,82,43,61,408,B
28,Faizan Khan,10029,62,40,92,99,47,63,71,474,A
36,Nouman Ali,10037,81,48,70,78,97,52,53,479,A
37,Owais Ahmed,10038,95,56,50,59,62,85,76,483,A
39,Huzaifa Ali,10040,78,95,53,71,62,75,50,484,A
41,Rayan Raza,10042,67,94,82,46,49,64,95,497,A
42,Adnan Ali,10043,44,89,58,70,49,60,72,442,B
44,Ubaid Raza,10045,83,56,69,83,67,48,89,495,A
45,Shayan Ali,10046,67,50,90,70,82,41,43,443,B
46,Ammar Ahmed,10047,48,50,40,62,87,93,96,476,A
48,Rehan Ali,10049,42,87,48,76,86,74,83,496,A
49,Mustafa Ahmed,10050,41,82,43,64,79,100,76,485,A
50,Shahmeer Raza,10051,92,88,44,80,63,45,56,468,A
54,Ayaan Ali,10055,50,70,70,72,49,91,43,445,B
56,Sami Raza,10057,67,97,68,40,69,60,67,468,A
57,Khalid Ali,10058,86,85,97,48,74,55,46,491,A
58,Afaq Ahmed,10059,51,70,45,94,72,81,40,453,A
59,Basit Raza,10060,46,97,56,78,56,89,65,487,A
60,Kamran Ali,10061,59,69,66,47,88,61,41,431,B
61,Murtaza Ahmed,10062,73,41,89,85,74,41,46,449,B
62,Furqan Raza,10063,60,76,99,54,61,43,93,486,A
64,Azlan Ahmed,10065,83,81,49,42,40,79,59,433,B
65,Awais Raza,10066,54,50,62,68,73,77,62,446,B
67,Naveed Ahmed,10068,90,80,59,76,55,54,66,480,A
68,Jibran Raza,10069,85,49,58,55,84,77,60,468,A
69,Abrar Ali,10070,66,44,49,69,55,65,54,402,B
70,Saif Ahmed,10071,85,59,76,68,77,50,72,487,A
75,Rameez Ali,10076,62,46,73,58,49,88,94,470,A
79,Hammad Ali,10080,49,67,79,68,50,51,93,457,A
82,Faisal Ali,10083,53,77,99,42,77,84,64,496,A
84,Sarmad Raza,10085,73,69,67,95,41,51,65,461,A
85,Atif Ali,10086,57,54,83,42,68,52,98,454,A
86,Waqar Ahmed,10087,48,72,43,59,67,85,70,444,B
87,Zayan Raza,10088,97,75,44,80,74,60,41,471,A
88,Akram Ali,10089,76,55,42,54,49,47,91,414,B
90,Mahad Ali,10091,44,80,62,53,83,76,97,495,A
93,Taimoor Ali,10094,60,69,44,72,94,46,56,441,B
96,Zubair Raza,10097,42,60,88,92,57,56,59,454,A
97,Ahmer Ali,10098,45,60,60,91,60,57,98,471,A
99,Dawood Raza,10100,82,62,42,80,54,49,43,412,B

In [38]:
df[df['ML'] < 65]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
0,Ahmed Raza,10001,52,64,52,74,51,49,70,412,B
2,Asad Ali,10003,60,97,73,57,52,80,50,469,A
4,Ali Hamza,10005,82,72,67,50,53,40,54,418,B
7,Fahad Khan,10008,93,94,99,47,54,51,41,479,A
8,Abdul Rehman,10009,93,58,51,92,62,93,66,515,A
12,Umer Farooq,10013,47,89,98,42,48,85,95,504,A
13,Salman Raza,10014,49,83,56,61,63,91,54,457,A
15,Imran Khan,10016,51,42,74,53,57,51,83,411,B
16,Noman Ahmed,10017,81,62,94,84,54,84,67,526,A
19,Waqas Ahmed,10020,81,47,82,67,41,82,52,452,A
20,Abdullah Naveed,10021,83,42,99,40,45,76,85,470,A
21,Mubashir Ali,10022,89,56,61,86,60,87,89,528,A
23,Arslan Ahmed,10024,52,83,44,94,57,55,90,475,A
26,Adeel Ahmed,10027,59,86,80,57,59,41,85,467,A
28,Faizan Khan,10029,62,40,92,99,47,63,71,474,A
29,Sameer Ahmed,10030,91,75,82,72,56,67,91,534,A
34,Irfan Ahmed,10035,94,66,85,87,64,65,76,537,A
37,Owais Ahmed,10038,95,56,50,59,62,85,76,483,A
39,Huzaifa Ali,10040,78,95,53,71,62,75,50,484,A
41,Rayan Raza,10042,67,94,82,46,49,64,95,497,A
42,Adnan Ali,10043,44,89,58,70,49,60,72,442,B
43,Farhan Ahmed,10044,94,87,43,62,50,94,71,501,A
50,Shahmeer Raza,10051,92,88,44,80,63,45,56,468,A
53,Muneeb Raza,10054,97,93,83,46,60,65,68,512,A
54,Ayaan Ali,10055,50,70,70,72,49,91,43,445,B
55,Areeb Ahmed,10056,75,93,80,63,58,70,87,526,A
59,Basit Raza,10060,46,97,56,78,56,89,65,487,A
62,Furqan Raza,10063,60,76,99,54,61,43,93,486,A
64,Azlan Ahmed,10065,83,81,49,42,40,79,59,433,B
67,Naveed Ahmed,10068,90,80,59,76,55,54,66,480,A
69,Abrar Ali,10070,66,44,49,69,55,65,54,402,B
73,Shahid Ahmed,10074,62,46,61,68,42,47,64,390,B
75,Rameez Ali,10076,62,46,73,58,49,88,94,470,A
77,Ahsan Raza,10078,43,88,91,78,62,81,62,505,A
79,Hammad Ali,10080,49,67,79,68,50,51,93,457,A
84,Sarmad Raza,10085,73,69,67,95,41,51,65,461,A
88,Akram Ali,10089,76,55,42,54,49,47,91,414,B
89,Haseeb Ahmed,10090,56,71,63,88,59,78,99,514,A
96,Zubair Raza,10097,42,60,88,92,57,56,59,454,A
97,Ahmer Ali,10098,45,60,60,91,60,57,98,471,A
99,Dawood Raza,10100,82,62,42,80,54,49,43,412,B

In [39]:
df[df['numpy'] > 75]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
2,Asad Ali,10003,60,97,73,57,52,80,50,469,A
3,Hassan Raza,10004,87,99,63,64,85,43,94,535,A
5,Usman Tariq,10006,91,88,62,64,80,65,49,499,A
6,Bilal Ahmed,10007,81,90,44,53,96,88,87,539,A
7,Fahad Khan,10008,93,94,99,47,54,51,41,479,A
9,Zain Ali,10010,71,100,71,93,73,88,85,581,A
10,Ahsan Iqbal,10011,48,87,76,45,83,41,55,435,B
11,Saad Ahmed,10012,75,100,99,48,80,60,76,538,A
12,Umer Farooq,10013,47,89,98,42,48,85,95,504,A
13,Salman Raza,10014,49,83,56,61,63,91,54,457,A
23,Arslan Ahmed,10024,52,83,44,94,57,55,90,475,A
24,Shoaib Malik,10025,72,82,72,68,98,55,73,520,A
26,Adeel Ahmed,10027,59,86,80,57,59,41,85,467,A
30,Haris Ali,10031,54,95,79,85,78,60,98,549,A
33,Zubair Ali,10034,77,98,60,42,100,100,62,539,A
38,Moiz Raza,10039,42,81,77,69,97,79,92,537,A
39,Huzaifa Ali,10040,78,95,53,71,62,75,50,484,A
41,Rayan Raza,10042,67,94,82,46,49,64,95,497,A
42,Adnan Ali,10043,44,89,58,70,49,60,72,442,B
43,Farhan Ahmed,10044,94,87,43,62,50,94,71,501,A
48,Rehan Ali,10049,42,87,48,76,86,74,83,496,A
49,Mustafa Ahmed,10050,41,82,43,64,79,100,76,485,A
50,Shahmeer Raza,10051,92,88,44,80,63,45,56,468,A
53,Muneeb Raza,10054,97,93,83,46,60,65,68,512,A
55,Areeb Ahmed,10056,75,93,80,63,58,70,87,526,A
56,Sami Raza,10057,67,97,68,40,69,60,67,468,A
57,Khalid Ali,10058,86,85,97,48,74,55,46,491,A
59,Basit Raza,10060,46,97,56,78,56,89,65,487,A
62,Furqan Raza,10063,60,76,99,54,61,43,93,486,A
64,Azlan Ahmed,10065,83,81,49,42,40,79,59,433,B
66,Sufyan Ali,10067,74,83,72,67,66,99,56,517,A
67,Naveed Ahmed,10068,90,80,59,76,55,54,66,480,A
72,Ehsan Ali,10073,83,77,47,80,71,79,77,514,A
76,Ismail Ahmed,10077,79,85,84,97,78,92,62,577,A
77,Ahsan Raza,10078,43,88,91,78,62,81,62,505,A
81,Shakir Raza,10082,99,95,77,47,84,98,58,558,A
82,Faisal Ali,10083,53,77,99,42,77,84,64,496,A
83,Amin Ahmed,10084,100,95,92,85,89,87,48,596,A
90,Mahad Ali,10091,44,80,62,53,83,76,97,495,A
91,Rohail Raza,10092,83,78,70,65,70,65,82,513,A
95,Hasnain Ahmed,10096,62,100,85,54,96,94,83,574,A

In [40]:
df[df['NLP'] < 50]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
5,Usman Tariq,10006,91,88,62,64,80,65,49,499,A
7,Fahad Khan,10008,93,94,99,47,54,51,41,479,A
32,Junaid Ahmed,10033,80,73,76,95,83,93,43,543,A
45,Shayan Ali,10046,67,50,90,70,82,41,43,443,B
54,Ayaan Ali,10055,50,70,70,72,49,91,43,445,B
57,Khalid Ali,10058,86,85,97,48,74,55,46,491,A
58,Afaq Ahmed,10059,51,70,45,94,72,81,40,453,A
60,Kamran Ali,10061,59,69,66,47,88,61,41,431,B
61,Murtaza Ahmed,10062,73,41,89,85,74,41,46,449,B
74,Zarar Raza,10075,87,48,66,88,74,98,44,505,A
80,Rizwan Ahmed,10081,85,40,74,96,84,93,40,512,A
83,Amin Ahmed,10084,100,95,92,85,89,87,48,596,A
87,Zayan Raza,10088,97,75,44,80,74,60,41,471,A
99,Dawood Raza,10100,82,62,42,80,54,49,43,412,B

In [41]:
df[df['streamlit'] > 80]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
8,Abdul Rehman,10009,93,58,51,92,62,93,66,515,A
9,Zain Ali,10010,71,100,71,93,73,88,85,581,A
14,Hamza Ali,10015,45,73,45,95,67,75,95,495,A
16,Noman Ahmed,10017,81,62,94,84,54,84,67,526,A
17,Shahzaib Ali,10018,90,54,96,88,81,96,98,603,A
21,Mubashir Ali,10022,89,56,61,86,60,87,89,528,A
23,Arslan Ahmed,10024,52,83,44,94,57,55,90,475,A
28,Faizan Khan,10029,62,40,92,99,47,63,71,474,A
30,Haris Ali,10031,54,95,79,85,78,60,98,549,A
32,Junaid Ahmed,10033,80,73,76,95,83,93,43,543,A
34,Irfan Ahmed,10035,94,66,85,87,64,65,76,537,A
35,Kashif Raza,10036,80,65,48,83,82,91,69,518,A
44,Ubaid Raza,10045,83,56,69,83,67,48,89,495,A
51,Zahid Ali,10052,78,44,60,93,98,61,73,507,A
58,Afaq Ahmed,10059,51,70,45,94,72,81,40,453,A
61,Murtaza Ahmed,10062,73,41,89,85,74,41,46,449,B
63,Ibrahim Ali,10064,91,58,56,100,98,49,93,545,A
74,Zarar Raza,10075,87,48,66,88,74,98,44,505,A
76,Ismail Ahmed,10077,79,85,84,97,78,92,62,577,A
78,Zain Ul Abidin,10079,56,61,71,90,65,66,92,501,A
80,Rizwan Ahmed,10081,85,40,74,96,84,93,40,512,A
83,Amin Ahmed,10084,100,95,92,85,89,87,48,596,A
84,Sarmad Raza,10085,73,69,67,95,41,51,65,461,A
89,Haseeb Ahmed,10090,56,71,63,88,59,78,99,514,A
96,Zubair Raza,10097,42,60,88,92,57,56,59,454,A
97,Ahmer Ali,10098,45,60,60,91,60,57,98,471,A
98,Nabeel Ahmed,10099,97,75,81,98,72,50,85,558,A

In [42]:
df[df['Grade'] == 'C']

Empty DataFrame
Columns: [name, roll num, python, numpy, pandas, streamlit, ML, DL, NLP, Total, Grade]
Index: []

In [43]:
df[df['python'] == 100]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
83,Amin Ahmed,10084,100,95,92,85,89,87,48,596,A

In [44]:
df[(df['python'] > 70) & (df['pandas'] > 65)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
1,Muhammad Asim,10002,85,53,78,61,86,46,53,462,A
4,Ali Hamza,10005,82,72,67,50,53,40,54,418,B
7,Fahad Khan,10008,93,94,99,47,54,51,41,479,A
9,Zain Ali,10010,71,100,71,93,73,88,85,581,A
11,Saad Ahmed,10012,75,100,99,48,80,60,76,538,A
16,Noman Ahmed,10017,81,62,94,84,54,84,67,526,A
17,Shahzaib Ali,10018,90,54,96,88,81,96,98,603,A
18,Danish Raza,10019,80,41,92,77,93,52,85,520,A
19,Waqas Ahmed,10020,81,47,82,67,41,82,52,452,A
20,Abdullah Naveed,10021,83,42,99,40,45,76,85,470,A
24,Shoaib Malik,10025,72,82,72,68,98,55,73,520,A
29,Sameer Ahmed,10030,91,75,82,72,56,67,91,534,A
32,Junaid Ahmed,10033,80,73,76,95,83,93,43,543,A
34,Irfan Ahmed,10035,94,66,85,87,64,65,76,537,A
36,Nouman Ali,10037,81,48,70,78,97,52,53,479,A
44,Ubaid Raza,10045,83,56,69,83,67,48,89,495,A
53,Muneeb Raza,10054,97,93,83,46,60,65,68,512,A
55,Areeb Ahmed,10056,75,93,80,63,58,70,87,526,A
57,Khalid Ali,10058,86,85,97,48,74,55,46,491,A
61,Murtaza Ahmed,10062,73,41,89,85,74,41,46,449,B
66,Sufyan Ali,10067,74,83,72,67,66,99,56,517,A
70,Saif Ahmed,10071,85,59,76,68,77,50,72,487,A
71,Rafay Raza,10072,90,43,97,50,88,81,75,524,A
74,Zarar Raza,10075,87,48,66,88,74,98,44,505,A
76,Ismail Ahmed,10077,79,85,84,97,78,92,62,577,A
80,Rizwan Ahmed,10081,85,40,74,96,84,93,40,512,A
81,Shakir Raza,10082,99,95,77,47,84,98,58,558,A
83,Amin Ahmed,10084,100,95,92,85,89,87,48,596,A
84,Sarmad Raza,10085,73,69,67,95,41,51,65,461,A
91,Rohail Raza,10092,83,78,70,65,70,65,82,513,A
92,Shahbaz Ahmed,10093,82,75,68,74,83,57,65,504,A
94,Affan Raza,10095,72,48,99,57,73,76,81,506,A
98,Nabeel Ahmed,10099,97,75,81,98,72,50,85,558,A

In [45]:
df[(df['ML'] < 60) | (df['DL'] < 50)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
0,Ahmed Raza,10001,52,64,52,74,51,49,70,412,B
1,Muhammad Asim,10002,85,53,78,61,86,46,53,462,A
2,Asad Ali,10003,60,97,73,57,52,80,50,469,A
3,Hassan Raza,10004,87,99,63,64,85,43,94,535,A
4,Ali Hamza,10005,82,72,67,50,53,40,54,418,B
7,Fahad Khan,10008,93,94,99,47,54,51,41,479,A
10,Ahsan Iqbal,10011,48,87,76,45,83,41,55,435,B
12,Umer Farooq,10013,47,89,98,42,48,85,95,504,A
15,Imran Khan,10016,51,42,74,53,57,51,83,411,B
16,Noman Ahmed,10017,81,62,94,84,54,84,67,526,A
19,Waqas Ahmed,10020,81,47,82,67,41,82,52,452,A
20,Abdullah Naveed,10021,83,42,99,40,45,76,85,470,A
23,Arslan Ahmed,10024,52,83,44,94,57,55,90,475,A
26,Adeel Ahmed,10027,59,86,80,57,59,41,85,467,A
27,Talha Raza,10028,77,42,45,58,82,43,61,408,B
28,Faizan Khan,10029,62,40,92,99,47,63,71,474,A
29,Sameer Ahmed,10030,91,75,82,72,56,67,91,534,A
41,Rayan Raza,10042,67,94,82,46,49,64,95,497,A
42,Adnan Ali,10043,44,89,58,70,49,60,72,442,B
43,Farhan Ahmed,10044,94,87,43,62,50,94,71,501,A
44,Ubaid Raza,10045,83,56,69,83,67,48,89,495,A
45,Shayan Ali,10046,67,50,90,70,82,41,43,443,B
50,Shahmeer Raza,10051,92,88,44,80,63,45,56,468,A
54,Ayaan Ali,10055,50,70,70,72,49,91,43,445,B
55,Areeb Ahmed,10056,75,93,80,63,58,70,87,526,A
59,Basit Raza,10060,46,97,56,78,56,89,65,487,A
61,Murtaza Ahmed,10062,73,41,89,85,74,41,46,449,B
62,Furqan Raza,10063,60,76,99,54,61,43,93,486,A
63,Ibrahim Ali,10064,91,58,56,100,98,49,93,545,A
64,Azlan Ahmed,10065,83,81,49,42,40,79,59,433,B
67,Naveed Ahmed,10068,90,80,59,76,55,54,66,480,A
69,Abrar Ali,10070,66,44,49,69,55,65,54,402,B
73,Shahid Ahmed,10074,62,46,61,68,42,47,64,390,B
75,Rameez Ali,10076,62,46,73,58,49,88,94,470,A
79,Hammad Ali,10080,49,67,79,68,50,51,93,457,A
84,Sarmad Raza,10085,73,69,67,95,41,51,65,461,A
88,Akram Ali,10089,76,55,42,54,49,47,91,414,B
89,Haseeb Ahmed,10090,56,71,63,88,59,78,99,514,A
93,Taimoor Ali,10094,60,69,44,72,94,46,56,441,B
96,Zubair Raza,10097,42,60,88,92,57,56,59,454,A
99,Dawood Raza,10100,82,62,42,80,54,49,43,412,B

In [46]:
df[(df['Grade'] == 'A') & (df['NLP'] > 60)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
3,Hassan Raza,10004,87,99,63,64,85,43,94,535,A
6,Bilal Ahmed,10007,81,90,44,53,96,88,87,539,A
8,Abdul Rehman,10009,93,58,51,92,62,93,66,515,A
9,Zain Ali,10010,71,100,71,93,73,88,85,581,A
11,Saad Ahmed,10012,75,100,99,48,80,60,76,538,A
...,...,...,...,...,...,...,...,...,...,...,...
92,Shahbaz Ahmed,10093,82,75,68,74,83,57,65,504,A
94,Affan Raza,10095,72,48,99,57,73,76,81,506,A
95,Hasnain Ahmed,10096,62,100,85,54,96,94,83,574,A
97,Ahmer Ali,10098,45,60,60,91,60,57,98,471,A
98,Nabeel Ahmed,10099,97,75,81,98,72,50,85,558,A

In [47]:
df[(df['Total'] > 500) & (df['streamlit'] < 60)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
6,Bilal Ahmed,10007,81,90,44,53,96,88,87,539,A
11,Saad Ahmed,10012,75,100,99,48,80,60,76,538,A
12,Umer Farooq,10013,47,89,98,42,48,85,95,504,A
31,Yasir Raza,10032,56,75,96,52,76,99,79,533,A
33,Zubair Ali,10034,77,98,60,42,100,100,62,539,A
53,Muneeb Raza,10054,97,93,83,46,60,65,68,512,A
71,Rafay Raza,10072,90,43,97,50,88,81,75,524,A
81,Shakir Raza,10082,99,95,77,47,84,98,58,558,A
94,Affan Raza,10095,72,48,99,57,73,76,81,506,A
95,Hasnain Ahmed,10096,62,100,85,54,96,94,83,574,A

In [48]:
df[(df['python'] > 75) & (df['numpy'] > 75) & (df['pandas'] > 75)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
7,Fahad Khan,10008,93,94,99,47,54,51,41,479,A
53,Muneeb Raza,10054,97,93,83,46,60,65,68,512,A
57,Khalid Ali,10058,86,85,97,48,74,55,46,491,A
76,Ismail Ahmed,10077,79,85,84,97,78,92,62,577,A
81,Shakir Raza,10082,99,95,77,47,84,98,58,558,A
83,Amin Ahmed,10084,100,95,92,85,89,87,48,596,A

In [49]:
df[(df['python'] < 50) & (df['numpy'] < 50)]

Empty DataFrame
Columns: [name, roll num, python, numpy, pandas, streamlit, ML, DL, NLP, Total, Grade]
Index: []

In [50]:
df[(df['ML'] > 60) & (df['DL'] > 60)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
5,Usman Tariq,10006,91,88,62,64,80,65,49,499,A
6,Bilal Ahmed,10007,81,90,44,53,96,88,87,539,A
8,Abdul Rehman,10009,93,58,51,92,62,93,66,515,A
9,Zain Ali,10010,71,100,71,93,73,88,85,581,A
13,Salman Raza,10014,49,83,56,61,63,91,54,457,A
14,Hamza Ali,10015,45,73,45,95,67,75,95,495,A
17,Shahzaib Ali,10018,90,54,96,88,81,96,98,603,A
22,Taha Raza,10023,42,56,88,63,95,76,75,495,A
25,Rizwan Ali,10026,66,48,99,74,81,81,97,546,A
31,Yasir Raza,10032,56,75,96,52,76,99,79,533,A
32,Junaid Ahmed,10033,80,73,76,95,83,93,43,543,A
33,Zubair Ali,10034,77,98,60,42,100,100,62,539,A
34,Irfan Ahmed,10035,94,66,85,87,64,65,76,537,A
35,Kashif Raza,10036,80,65,48,83,82,91,69,518,A
37,Owais Ahmed,10038,95,56,50,59,62,85,76,483,A
38,Moiz Raza,10039,42,81,77,69,97,79,92,537,A
39,Huzaifa Ali,10040,78,95,53,71,62,75,50,484,A
40,Anas Ahmed,10041,60,69,90,66,93,85,79,542,A
46,Ammar Ahmed,10047,48,50,40,62,87,93,96,476,A
47,Zeeshan Raza,10048,41,74,87,60,91,96,61,510,A
48,Rehan Ali,10049,42,87,48,76,86,74,83,496,A
49,Mustafa Ahmed,10050,41,82,43,64,79,100,76,485,A
51,Zahid Ali,10052,78,44,60,93,98,61,73,507,A
52,Qasim Ahmed,10053,95,60,44,70,97,93,76,535,A
58,Afaq Ahmed,10059,51,70,45,94,72,81,40,453,A
60,Kamran Ali,10061,59,69,66,47,88,61,41,431,B
65,Awais Raza,10066,54,50,62,68,73,77,62,446,B
66,Sufyan Ali,10067,74,83,72,67,66,99,56,517,A
68,Jibran Raza,10069,85,49,58,55,84,77,60,468,A
71,Rafay Raza,10072,90,43,97,50,88,81,75,524,A
72,Ehsan Ali,10073,83,77,47,80,71,79,77,514,A
74,Zarar Raza,10075,87,48,66,88,74,98,44,505,A
76,Ismail Ahmed,10077,79,85,84,97,78,92,62,577,A
77,Ahsan Raza,10078,43,88,91,78,62,81,62,505,A
78,Zain Ul Abidin,10079,56,61,71,90,65,66,92,501,A
80,Rizwan Ahmed,10081,85,40,74,96,84,93,40,512,A
81,Shakir Raza,10082,99,95,77,47,84,98,58,558,A
82,Faisal Ali,10083,53,77,99,42,77,84,64,496,A
83,Amin Ahmed,10084,100,95,92,85,89,87,48,596,A
86,Waqar Ahmed,10087,48,72,43,59,67,85,70,444,B
90,Mahad Ali,10091,44,80,62,53,83,76,97,495,A
91,Rohail Raza,10092,83,78,70,65,70,65,82,513,A
94,Affan Raza,10095,72,48,99,57,73,76,81,506,A
95,Hasnain Ahmed,10096,62,100,85,54,96,94,83,574,A

In [51]:
df[(df['python'] > 80) & (df['NLP'] < 60)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
1,Muhammad Asim,10002,85,53,78,61,86,46,53,462,A
4,Ali Hamza,10005,82,72,67,50,53,40,54,418,B
5,Usman Tariq,10006,91,88,62,64,80,65,49,499,A
7,Fahad Khan,10008,93,94,99,47,54,51,41,479,A
19,Waqas Ahmed,10020,81,47,82,67,41,82,52,452,A
36,Nouman Ali,10037,81,48,70,78,97,52,53,479,A
50,Shahmeer Raza,10051,92,88,44,80,63,45,56,468,A
57,Khalid Ali,10058,86,85,97,48,74,55,46,491,A
64,Azlan Ahmed,10065,83,81,49,42,40,79,59,433,B
74,Zarar Raza,10075,87,48,66,88,74,98,44,505,A
80,Rizwan Ahmed,10081,85,40,74,96,84,93,40,512,A
81,Shakir Raza,10082,99,95,77,47,84,98,58,558,A
83,Amin Ahmed,10084,100,95,92,85,89,87,48,596,A
87,Zayan Raza,10088,97,75,44,80,74,60,41,471,A
99,Dawood Raza,10100,82,62,42,80,54,49,43,412,B

In [52]:
df[(df['Total'] < 450) & (df['Grade'] == 'B')]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
0,Ahmed Raza,10001,52,64,52,74,51,49,70,412,B
4,Ali Hamza,10005,82,72,67,50,53,40,54,418,B
10,Ahsan Iqbal,10011,48,87,76,45,83,41,55,435,B
15,Imran Khan,10016,51,42,74,53,57,51,83,411,B
27,Talha Raza,10028,77,42,45,58,82,43,61,408,B
42,Adnan Ali,10043,44,89,58,70,49,60,72,442,B
45,Shayan Ali,10046,67,50,90,70,82,41,43,443,B
54,Ayaan Ali,10055,50,70,70,72,49,91,43,445,B
60,Kamran Ali,10061,59,69,66,47,88,61,41,431,B
61,Murtaza Ahmed,10062,73,41,89,85,74,41,46,449,B
64,Azlan Ahmed,10065,83,81,49,42,40,79,59,433,B
65,Awais Raza,10066,54,50,62,68,73,77,62,446,B
69,Abrar Ali,10070,66,44,49,69,55,65,54,402,B
73,Shahid Ahmed,10074,62,46,61,68,42,47,64,390,B
86,Waqar Ahmed,10087,48,72,43,59,67,85,70,444,B
88,Akram Ali,10089,76,55,42,54,49,47,91,414,B
93,Taimoor Ali,10094,60,69,44,72,94,46,56,441,B
99,Dawood Raza,10100,82,62,42,80,54,49,43,412,B

In [53]:
df[(df['pandas'] > 70) | (df['NLP'] > 70)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
1,Muhammad Asim,10002,85,53,78,61,86,46,53,462,A
2,Asad Ali,10003,60,97,73,57,52,80,50,469,A
3,Hassan Raza,10004,87,99,63,64,85,43,94,535,A
6,Bilal Ahmed,10007,81,90,44,53,96,88,87,539,A
7,Fahad Khan,10008,93,94,99,47,54,51,41,479,A
...,...,...,...,...,...,...,...,...,...,...,...
94,Affan Raza,10095,72,48,99,57,73,76,81,506,A
95,Hasnain Ahmed,10096,62,100,85,54,96,94,83,574,A
96,Zubair Raza,10097,42,60,88,92,57,56,59,454,A
97,Ahmer Ali,10098,45,60,60,91,60,57,98,471,A
98,Nabeel Ahmed,10099,97,75,81,98,72,50,85,558,A

In [54]:
df[(df['python'] < 60) & (df['numpy'] < 60) & (df['pandas'] < 60)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
46,Ammar Ahmed,10047,48,50,40,62,87,93,96,476,A

In [55]:
df[(df['ML'] > 65) & (df['NLP'] > 65)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
3,Hassan Raza,10004,87,99,63,64,85,43,94,535,A
6,Bilal Ahmed,10007,81,90,44,53,96,88,87,539,A
9,Zain Ali,10010,71,100,71,93,73,88,85,581,A
11,Saad Ahmed,10012,75,100,99,48,80,60,76,538,A
14,Hamza Ali,10015,45,73,45,95,67,75,95,495,A
17,Shahzaib Ali,10018,90,54,96,88,81,96,98,603,A
18,Danish Raza,10019,80,41,92,77,93,52,85,520,A
22,Taha Raza,10023,42,56,88,63,95,76,75,495,A
24,Shoaib Malik,10025,72,82,72,68,98,55,73,520,A
25,Rizwan Ali,10026,66,48,99,74,81,81,97,546,A
30,Haris Ali,10031,54,95,79,85,78,60,98,549,A
31,Yasir Raza,10032,56,75,96,52,76,99,79,533,A
35,Kashif Raza,10036,80,65,48,83,82,91,69,518,A
38,Moiz Raza,10039,42,81,77,69,97,79,92,537,A
40,Anas Ahmed,10041,60,69,90,66,93,85,79,542,A
44,Ubaid Raza,10045,83,56,69,83,67,48,89,495,A
46,Ammar Ahmed,10047,48,50,40,62,87,93,96,476,A
48,Rehan Ali,10049,42,87,48,76,86,74,83,496,A
49,Mustafa Ahmed,10050,41,82,43,64,79,100,76,485,A
51,Zahid Ali,10052,78,44,60,93,98,61,73,507,A
52,Qasim Ahmed,10053,95,60,44,70,97,93,76,535,A
56,Sami Raza,10057,67,97,68,40,69,60,67,468,A
63,Ibrahim Ali,10064,91,58,56,100,98,49,93,545,A
70,Saif Ahmed,10071,85,59,76,68,77,50,72,487,A
71,Rafay Raza,10072,90,43,97,50,88,81,75,524,A
72,Ehsan Ali,10073,83,77,47,80,71,79,77,514,A
85,Atif Ali,10086,57,54,83,42,68,52,98,454,A
86,Waqar Ahmed,10087,48,72,43,59,67,85,70,444,B
90,Mahad Ali,10091,44,80,62,53,83,76,97,495,A
91,Rohail Raza,10092,83,78,70,65,70,65,82,513,A
94,Affan Raza,10095,72,48,99,57,73,76,81,506,A
95,Hasnain Ahmed,10096,62,100,85,54,96,94,83,574,A
98,Nabeel Ahmed,10099,97,75,81,98,72,50,85,558,A

In [56]:
df[(df['ML'] > 65) & (df['NLP'] > 65)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
3,Hassan Raza,10004,87,99,63,64,85,43,94,535,A
6,Bilal Ahmed,10007,81,90,44,53,96,88,87,539,A
9,Zain Ali,10010,71,100,71,93,73,88,85,581,A
11,Saad Ahmed,10012,75,100,99,48,80,60,76,538,A
14,Hamza Ali,10015,45,73,45,95,67,75,95,495,A
17,Shahzaib Ali,10018,90,54,96,88,81,96,98,603,A
18,Danish Raza,10019,80,41,92,77,93,52,85,520,A
22,Taha Raza,10023,42,56,88,63,95,76,75,495,A
24,Shoaib Malik,10025,72,82,72,68,98,55,73,520,A
25,Rizwan Ali,10026,66,48,99,74,81,81,97,546,A
30,Haris Ali,10031,54,95,79,85,78,60,98,549,A
31,Yasir Raza,10032,56,75,96,52,76,99,79,533,A
35,Kashif Raza,10036,80,65,48,83,82,91,69,518,A
38,Moiz Raza,10039,42,81,77,69,97,79,92,537,A
40,Anas Ahmed,10041,60,69,90,66,93,85,79,542,A
44,Ubaid Raza,10045,83,56,69,83,67,48,89,495,A
46,Ammar Ahmed,10047,48,50,40,62,87,93,96,476,A
48,Rehan Ali,10049,42,87,48,76,86,74,83,496,A
49,Mustafa Ahmed,10050,41,82,43,64,79,100,76,485,A
51,Zahid Ali,10052,78,44,60,93,98,61,73,507,A
52,Qasim Ahmed,10053,95,60,44,70,97,93,76,535,A
56,Sami Raza,10057,67,97,68,40,69,60,67,468,A
63,Ibrahim Ali,10064,91,58,56,100,98,49,93,545,A
70,Saif Ahmed,10071,85,59,76,68,77,50,72,487,A
71,Rafay Raza,10072,90,43,97,50,88,81,75,524,A
72,Ehsan Ali,10073,83,77,47,80,71,79,77,514,A
85,Atif Ali,10086,57,54,83,42,68,52,98,454,A
86,Waqar Ahmed,10087,48,72,43,59,67,85,70,444,B
90,Mahad Ali,10091,44,80,62,53,83,76,97,495,A
91,Rohail Raza,10092,83,78,70,65,70,65,82,513,A
94,Affan Raza,10095,72,48,99,57,73,76,81,506,A
95,Hasnain Ahmed,10096,62,100,85,54,96,94,83,574,A
98,Nabeel Ahmed,10099,97,75,81,98,72,50,85,558,A

In [57]:
df[(df['Grade'] == 'A') & (df['DL'] < 55)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
1,Muhammad Asim,10002,85,53,78,61,86,46,53,462,A
3,Hassan Raza,10004,87,99,63,64,85,43,94,535,A
7,Fahad Khan,10008,93,94,99,47,54,51,41,479,A
18,Danish Raza,10019,80,41,92,77,93,52,85,520,A
26,Adeel Ahmed,10027,59,86,80,57,59,41,85,467,A
36,Nouman Ali,10037,81,48,70,78,97,52,53,479,A
44,Ubaid Raza,10045,83,56,69,83,67,48,89,495,A
50,Shahmeer Raza,10051,92,88,44,80,63,45,56,468,A
62,Furqan Raza,10063,60,76,99,54,61,43,93,486,A
63,Ibrahim Ali,10064,91,58,56,100,98,49,93,545,A
67,Naveed Ahmed,10068,90,80,59,76,55,54,66,480,A
70,Saif Ahmed,10071,85,59,76,68,77,50,72,487,A
79,Hammad Ali,10080,49,67,79,68,50,51,93,457,A
84,Sarmad Raza,10085,73,69,67,95,41,51,65,461,A
85,Atif Ali,10086,57,54,83,42,68,52,98,454,A
98,Nabeel Ahmed,10099,97,75,81,98,72,50,85,558,A

In [58]:
df[(df['Grade'] == 'A') & (df['DL'] < 55)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
1,Muhammad Asim,10002,85,53,78,61,86,46,53,462,A
3,Hassan Raza,10004,87,99,63,64,85,43,94,535,A
7,Fahad Khan,10008,93,94,99,47,54,51,41,479,A
18,Danish Raza,10019,80,41,92,77,93,52,85,520,A
26,Adeel Ahmed,10027,59,86,80,57,59,41,85,467,A
36,Nouman Ali,10037,81,48,70,78,97,52,53,479,A
44,Ubaid Raza,10045,83,56,69,83,67,48,89,495,A
50,Shahmeer Raza,10051,92,88,44,80,63,45,56,468,A
62,Furqan Raza,10063,60,76,99,54,61,43,93,486,A
63,Ibrahim Ali,10064,91,58,56,100,98,49,93,545,A
67,Naveed Ahmed,10068,90,80,59,76,55,54,66,480,A
70,Saif Ahmed,10071,85,59,76,68,77,50,72,487,A
79,Hammad Ali,10080,49,67,79,68,50,51,93,457,A
84,Sarmad Raza,10085,73,69,67,95,41,51,65,461,A
85,Atif Ali,10086,57,54,83,42,68,52,98,454,A
98,Nabeel Ahmed,10099,97,75,81,98,72,50,85,558,A

In [59]:
df[(df['streamlit'] > 70) & (df['pandas'] > 70)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
9,Zain Ali,10010,71,100,71,93,73,88,85,581,A
16,Noman Ahmed,10017,81,62,94,84,54,84,67,526,A
17,Shahzaib Ali,10018,90,54,96,88,81,96,98,603,A
18,Danish Raza,10019,80,41,92,77,93,52,85,520,A
25,Rizwan Ali,10026,66,48,99,74,81,81,97,546,A
28,Faizan Khan,10029,62,40,92,99,47,63,71,474,A
29,Sameer Ahmed,10030,91,75,82,72,56,67,91,534,A
30,Haris Ali,10031,54,95,79,85,78,60,98,549,A
32,Junaid Ahmed,10033,80,73,76,95,83,93,43,543,A
34,Irfan Ahmed,10035,94,66,85,87,64,65,76,537,A
61,Murtaza Ahmed,10062,73,41,89,85,74,41,46,449,B
76,Ismail Ahmed,10077,79,85,84,97,78,92,62,577,A
77,Ahsan Raza,10078,43,88,91,78,62,81,62,505,A
78,Zain Ul Abidin,10079,56,61,71,90,65,66,92,501,A
80,Rizwan Ahmed,10081,85,40,74,96,84,93,40,512,A
83,Amin Ahmed,10084,100,95,92,85,89,87,48,596,A
96,Zubair Raza,10097,42,60,88,92,57,56,59,454,A
98,Nabeel Ahmed,10099,97,75,81,98,72,50,85,558,A

In [60]:
subjects = ['python', 'numpy', 'pandas', 'streamlit', 'ML', 'DL', 'NLP']
df[(df[subjects] < 50).any(axis=1)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
0,Ahmed Raza,10001,52,64,52,74,51,49,70,412,B
1,Muhammad Asim,10002,85,53,78,61,86,46,53,462,A
3,Hassan Raza,10004,87,99,63,64,85,43,94,535,A
4,Ali Hamza,10005,82,72,67,50,53,40,54,418,B
5,Usman Tariq,10006,91,88,62,64,80,65,49,499,A
...,...,...,...,...,...,...,...,...,...,...,...
93,Taimoor Ali,10094,60,69,44,72,94,46,56,441,B
94,Affan Raza,10095,72,48,99,57,73,76,81,506,A
96,Zubair Raza,10097,42,60,88,92,57,56,59,454,A
97,Ahmer Ali,10098,45,60,60,91,60,57,98,471,A
99,Dawood Raza,10100,82,62,42,80,54,49,43,412,B

In [61]:
df[(df[subjects] > 90).any(axis=1)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
2,Asad Ali,10003,60,97,73,57,52,80,50,469,A
3,Hassan Raza,10004,87,99,63,64,85,43,94,535,A
5,Usman Tariq,10006,91,88,62,64,80,65,49,499,A
6,Bilal Ahmed,10007,81,90,44,53,96,88,87,539,A
7,Fahad Khan,10008,93,94,99,47,54,51,41,479,A
...,...,...,...,...,...,...,...,...,...,...,...
94,Affan Raza,10095,72,48,99,57,73,76,81,506,A
95,Hasnain Ahmed,10096,62,100,85,54,96,94,83,574,A
96,Zubair Raza,10097,42,60,88,92,57,56,59,454,A
97,Ahmer Ali,10098,45,60,60,91,60,57,98,471,A
98,Nabeel Ahmed,10099,97,75,81,98,72,50,85,558,A

In [62]:
df[df['Total'].between(480, 520)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
5,Usman Tariq,10006,91,88,62,64,80,65,49,499,A
8,Abdul Rehman,10009,93,58,51,92,62,93,66,515,A
12,Umer Farooq,10013,47,89,98,42,48,85,95,504,A
14,Hamza Ali,10015,45,73,45,95,67,75,95,495,A
18,Danish Raza,10019,80,41,92,77,93,52,85,520,A
22,Taha Raza,10023,42,56,88,63,95,76,75,495,A
24,Shoaib Malik,10025,72,82,72,68,98,55,73,520,A
35,Kashif Raza,10036,80,65,48,83,82,91,69,518,A
37,Owais Ahmed,10038,95,56,50,59,62,85,76,483,A
39,Huzaifa Ali,10040,78,95,53,71,62,75,50,484,A
41,Rayan Raza,10042,67,94,82,46,49,64,95,497,A
43,Farhan Ahmed,10044,94,87,43,62,50,94,71,501,A
44,Ubaid Raza,10045,83,56,69,83,67,48,89,495,A
47,Zeeshan Raza,10048,41,74,87,60,91,96,61,510,A
48,Rehan Ali,10049,42,87,48,76,86,74,83,496,A
49,Mustafa Ahmed,10050,41,82,43,64,79,100,76,485,A
51,Zahid Ali,10052,78,44,60,93,98,61,73,507,A
53,Muneeb Raza,10054,97,93,83,46,60,65,68,512,A
57,Khalid Ali,10058,86,85,97,48,74,55,46,491,A
59,Basit Raza,10060,46,97,56,78,56,89,65,487,A
62,Furqan Raza,10063,60,76,99,54,61,43,93,486,A
66,Sufyan Ali,10067,74,83,72,67,66,99,56,517,A
67,Naveed Ahmed,10068,90,80,59,76,55,54,66,480,A
70,Saif Ahmed,10071,85,59,76,68,77,50,72,487,A
72,Ehsan Ali,10073,83,77,47,80,71,79,77,514,A
74,Zarar Raza,10075,87,48,66,88,74,98,44,505,A
77,Ahsan Raza,10078,43,88,91,78,62,81,62,505,A
78,Zain Ul Abidin,10079,56,61,71,90,65,66,92,501,A
80,Rizwan Ahmed,10081,85,40,74,96,84,93,40,512,A
82,Faisal Ali,10083,53,77,99,42,77,84,64,496,A
89,Haseeb Ahmed,10090,56,71,63,88,59,78,99,514,A
90,Mahad Ali,10091,44,80,62,53,83,76,97,495,A
91,Rohail Raza,10092,83,78,70,65,70,65,82,513,A
92,Shahbaz Ahmed,10093,82,75,68,74,83,57,65,504,A
94,Affan Raza,10095,72,48,99,57,73,76,81,506,A

In [63]:
df[df['Total'].between(480, 520)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
5,Usman Tariq,10006,91,88,62,64,80,65,49,499,A
8,Abdul Rehman,10009,93,58,51,92,62,93,66,515,A
12,Umer Farooq,10013,47,89,98,42,48,85,95,504,A
14,Hamza Ali,10015,45,73,45,95,67,75,95,495,A
18,Danish Raza,10019,80,41,92,77,93,52,85,520,A
22,Taha Raza,10023,42,56,88,63,95,76,75,495,A
24,Shoaib Malik,10025,72,82,72,68,98,55,73,520,A
35,Kashif Raza,10036,80,65,48,83,82,91,69,518,A
37,Owais Ahmed,10038,95,56,50,59,62,85,76,483,A
39,Huzaifa Ali,10040,78,95,53,71,62,75,50,484,A
41,Rayan Raza,10042,67,94,82,46,49,64,95,497,A
43,Farhan Ahmed,10044,94,87,43,62,50,94,71,501,A
44,Ubaid Raza,10045,83,56,69,83,67,48,89,495,A
47,Zeeshan Raza,10048,41,74,87,60,91,96,61,510,A
48,Rehan Ali,10049,42,87,48,76,86,74,83,496,A
49,Mustafa Ahmed,10050,41,82,43,64,79,100,76,485,A
51,Zahid Ali,10052,78,44,60,93,98,61,73,507,A
53,Muneeb Raza,10054,97,93,83,46,60,65,68,512,A
57,Khalid Ali,10058,86,85,97,48,74,55,46,491,A
59,Basit Raza,10060,46,97,56,78,56,89,65,487,A
62,Furqan Raza,10063,60,76,99,54,61,43,93,486,A
66,Sufyan Ali,10067,74,83,72,67,66,99,56,517,A
67,Naveed Ahmed,10068,90,80,59,76,55,54,66,480,A
70,Saif Ahmed,10071,85,59,76,68,77,50,72,487,A
72,Ehsan Ali,10073,83,77,47,80,71,79,77,514,A
74,Zarar Raza,10075,87,48,66,88,74,98,44,505,A
77,Ahsan Raza,10078,43,88,91,78,62,81,62,505,A
78,Zain Ul Abidin,10079,56,61,71,90,65,66,92,501,A
80,Rizwan Ahmed,10081,85,40,74,96,84,93,40,512,A
82,Faisal Ali,10083,53,77,99,42,77,84,64,496,A
89,Haseeb Ahmed,10090,56,71,63,88,59,78,99,514,A
90,Mahad Ali,10091,44,80,62,53,83,76,97,495,A
91,Rohail Raza,10092,83,78,70,65,70,65,82,513,A
92,Shahbaz Ahmed,10093,82,75,68,74,83,57,65,504,A
94,Affan Raza,10095,72,48,99,57,73,76,81,506,A

In [64]:
df[(df['python'] > 60) & (df['numpy'] < 60)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
1,Muhammad Asim,10002,85,53,78,61,86,46,53,462,A
8,Abdul Rehman,10009,93,58,51,92,62,93,66,515,A
17,Shahzaib Ali,10018,90,54,96,88,81,96,98,603,A
18,Danish Raza,10019,80,41,92,77,93,52,85,520,A
19,Waqas Ahmed,10020,81,47,82,67,41,82,52,452,A
20,Abdullah Naveed,10021,83,42,99,40,45,76,85,470,A
21,Mubashir Ali,10022,89,56,61,86,60,87,89,528,A
25,Rizwan Ali,10026,66,48,99,74,81,81,97,546,A
27,Talha Raza,10028,77,42,45,58,82,43,61,408,B
28,Faizan Khan,10029,62,40,92,99,47,63,71,474,A
36,Nouman Ali,10037,81,48,70,78,97,52,53,479,A
37,Owais Ahmed,10038,95,56,50,59,62,85,76,483,A
44,Ubaid Raza,10045,83,56,69,83,67,48,89,495,A
45,Shayan Ali,10046,67,50,90,70,82,41,43,443,B
51,Zahid Ali,10052,78,44,60,93,98,61,73,507,A
61,Murtaza Ahmed,10062,73,41,89,85,74,41,46,449,B
63,Ibrahim Ali,10064,91,58,56,100,98,49,93,545,A
68,Jibran Raza,10069,85,49,58,55,84,77,60,468,A
69,Abrar Ali,10070,66,44,49,69,55,65,54,402,B
70,Saif Ahmed,10071,85,59,76,68,77,50,72,487,A
71,Rafay Raza,10072,90,43,97,50,88,81,75,524,A
73,Shahid Ahmed,10074,62,46,61,68,42,47,64,390,B
74,Zarar Raza,10075,87,48,66,88,74,98,44,505,A
75,Rameez Ali,10076,62,46,73,58,49,88,94,470,A
80,Rizwan Ahmed,10081,85,40,74,96,84,93,40,512,A
88,Akram Ali,10089,76,55,42,54,49,47,91,414,B
94,Affan Raza,10095,72,48,99,57,73,76,81,506,A

In [65]:
df[(df['python'] > 60) & (df['numpy'] < 60)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
1,Muhammad Asim,10002,85,53,78,61,86,46,53,462,A
8,Abdul Rehman,10009,93,58,51,92,62,93,66,515,A
17,Shahzaib Ali,10018,90,54,96,88,81,96,98,603,A
18,Danish Raza,10019,80,41,92,77,93,52,85,520,A
19,Waqas Ahmed,10020,81,47,82,67,41,82,52,452,A
20,Abdullah Naveed,10021,83,42,99,40,45,76,85,470,A
21,Mubashir Ali,10022,89,56,61,86,60,87,89,528,A
25,Rizwan Ali,10026,66,48,99,74,81,81,97,546,A
27,Talha Raza,10028,77,42,45,58,82,43,61,408,B
28,Faizan Khan,10029,62,40,92,99,47,63,71,474,A
36,Nouman Ali,10037,81,48,70,78,97,52,53,479,A
37,Owais Ahmed,10038,95,56,50,59,62,85,76,483,A
44,Ubaid Raza,10045,83,56,69,83,67,48,89,495,A
45,Shayan Ali,10046,67,50,90,70,82,41,43,443,B
51,Zahid Ali,10052,78,44,60,93,98,61,73,507,A
61,Murtaza Ahmed,10062,73,41,89,85,74,41,46,449,B
63,Ibrahim Ali,10064,91,58,56,100,98,49,93,545,A
68,Jibran Raza,10069,85,49,58,55,84,77,60,468,A
69,Abrar Ali,10070,66,44,49,69,55,65,54,402,B
70,Saif Ahmed,10071,85,59,76,68,77,50,72,487,A
71,Rafay Raza,10072,90,43,97,50,88,81,75,524,A
73,Shahid Ahmed,10074,62,46,61,68,42,47,64,390,B
74,Zarar Raza,10075,87,48,66,88,74,98,44,505,A
75,Rameez Ali,10076,62,46,73,58,49,88,94,470,A
80,Rizwan Ahmed,10081,85,40,74,96,84,93,40,512,A
88,Akram Ali,10089,76,55,42,54,49,47,91,414,B
94,Affan Raza,10095,72,48,99,57,73,76,81,506,A

In [66]:
df[(df['Grade'] == 'B') & (df['ML'] > 70)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
10,Ahsan Iqbal,10011,48,87,76,45,83,41,55,435,B
27,Talha Raza,10028,77,42,45,58,82,43,61,408,B
45,Shayan Ali,10046,67,50,90,70,82,41,43,443,B
60,Kamran Ali,10061,59,69,66,47,88,61,41,431,B
61,Murtaza Ahmed,10062,73,41,89,85,74,41,46,449,B
65,Awais Raza,10066,54,50,62,68,73,77,62,446,B
93,Taimoor Ali,10094,60,69,44,72,94,46,56,441,B

In [67]:
df[df['NLP'] > df['DL']]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
0,Ahmed Raza,10001,52,64,52,74,51,49,70,412,B
1,Muhammad Asim,10002,85,53,78,61,86,46,53,462,A
3,Hassan Raza,10004,87,99,63,64,85,43,94,535,A
4,Ali Hamza,10005,82,72,67,50,53,40,54,418,B
10,Ahsan Iqbal,10011,48,87,76,45,83,41,55,435,B
11,Saad Ahmed,10012,75,100,99,48,80,60,76,538,A
12,Umer Farooq,10013,47,89,98,42,48,85,95,504,A
14,Hamza Ali,10015,45,73,45,95,67,75,95,495,A
15,Imran Khan,10016,51,42,74,53,57,51,83,411,B
17,Shahzaib Ali,10018,90,54,96,88,81,96,98,603,A
18,Danish Raza,10019,80,41,92,77,93,52,85,520,A
20,Abdullah Naveed,10021,83,42,99,40,45,76,85,470,A
21,Mubashir Ali,10022,89,56,61,86,60,87,89,528,A
23,Arslan Ahmed,10024,52,83,44,94,57,55,90,475,A
24,Shoaib Malik,10025,72,82,72,68,98,55,73,520,A
25,Rizwan Ali,10026,66,48,99,74,81,81,97,546,A
26,Adeel Ahmed,10027,59,86,80,57,59,41,85,467,A
27,Talha Raza,10028,77,42,45,58,82,43,61,408,B
28,Faizan Khan,10029,62,40,92,99,47,63,71,474,A
29,Sameer Ahmed,10030,91,75,82,72,56,67,91,534,A
30,Haris Ali,10031,54,95,79,85,78,60,98,549,A
34,Irfan Ahmed,10035,94,66,85,87,64,65,76,537,A
36,Nouman Ali,10037,81,48,70,78,97,52,53,479,A
38,Moiz Raza,10039,42,81,77,69,97,79,92,537,A
41,Rayan Raza,10042,67,94,82,46,49,64,95,497,A
42,Adnan Ali,10043,44,89,58,70,49,60,72,442,B
44,Ubaid Raza,10045,83,56,69,83,67,48,89,495,A
45,Shayan Ali,10046,67,50,90,70,82,41,43,443,B
46,Ammar Ahmed,10047,48,50,40,62,87,93,96,476,A
48,Rehan Ali,10049,42,87,48,76,86,74,83,496,A
50,Shahmeer Raza,10051,92,88,44,80,63,45,56,468,A
51,Zahid Ali,10052,78,44,60,93,98,61,73,507,A
53,Muneeb Raza,10054,97,93,83,46,60,65,68,512,A
55,Areeb Ahmed,10056,75,93,80,63,58,70,87,526,A
56,Sami Raza,10057,67,97,68,40,69,60,67,468,A
61,Murtaza Ahmed,10062,73,41,89,85,74,41,46,449,B
62,Furqan Raza,10063,60,76,99,54,61,43,93,486,A
63,Ibrahim Ali,10064,91,58,56,100,98,49,93,545,A
67,Naveed Ahmed,10068,90,80,59,76,55,54,66,480,A
70,Saif Ahmed,10071,85,59,76,68,77,50,72,487,A
73,Shahid Ahmed,10074,62,46,61,68,42,47,64,390,B
75,Rameez Ali,10076,62,46,73,58,49,88,94,470,A
78,Zain Ul Abidin,10079,56,61,71,90,65,66,92,501,A
79,Hammad Ali,10080,49,67,79,68,50,51,93,457,A
84,Sarmad Raza,10085,73,69,67,95,41,51,65,461,A
85,Atif Ali,10086,57,54,83,42,68,52,98,454,A
88,Akram Ali,10089,76,55,42,54,49,47,91,414,B
89,Haseeb Ahmed,10090,56,71,63,88,59,78,99,514,A
90,Mahad Ali,10091,44,80,62,53,83,76,97,495,A
91,Rohail Raza,10092,83,78,70,65,70,65,82,513,A
92,Shahbaz Ahmed,10093,82,75,68,74,83,57,65,504,A
93,Taimoor Ali,10094,60,69,44,72,94,46,56,441,B
94,Affan Raza,10095,72,48,99,57,73,76,81,506,A
96,Zubair Raza,10097,42,60,88,92,57,56,59,454,A
97,Ahmer Ali,10098,45,60,60,91,60,57,98,471,A
98,Nabeel Ahmed,10099,97,75,81,98,72,50,85,558,A

In [68]:
df[(df['python'] > 70) & (df['numpy'] > 70) & (df['pandas'] > 70)]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
7,Fahad Khan,10008,93,94,99,47,54,51,41,479,A
9,Zain Ali,10010,71,100,71,93,73,88,85,581,A
11,Saad Ahmed,10012,75,100,99,48,80,60,76,538,A
24,Shoaib Malik,10025,72,82,72,68,98,55,73,520,A
29,Sameer Ahmed,10030,91,75,82,72,56,67,91,534,A
32,Junaid Ahmed,10033,80,73,76,95,83,93,43,543,A
53,Muneeb Raza,10054,97,93,83,46,60,65,68,512,A
55,Areeb Ahmed,10056,75,93,80,63,58,70,87,526,A
57,Khalid Ali,10058,86,85,97,48,74,55,46,491,A
66,Sufyan Ali,10067,74,83,72,67,66,99,56,517,A
76,Ismail Ahmed,10077,79,85,84,97,78,92,62,577,A
81,Shakir Raza,10082,99,95,77,47,84,98,58,558,A
83,Amin Ahmed,10084,100,95,92,85,89,87,48,596,A
98,Nabeel Ahmed,10099,97,75,81,98,72,50,85,558,A

In [69]:
df[(df['python'] + df['numpy'] + df['pandas']) > 200]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
1,Muhammad Asim,10002,85,53,78,61,86,46,53,462,A
2,Asad Ali,10003,60,97,73,57,52,80,50,469,A
3,Hassan Raza,10004,87,99,63,64,85,43,94,535,A
4,Ali Hamza,10005,82,72,67,50,53,40,54,418,B
5,Usman Tariq,10006,91,88,62,64,80,65,49,499,A
...,...,...,...,...,...,...,...,...,...,...,...
91,Rohail Raza,10092,83,78,70,65,70,65,82,513,A
92,Shahbaz Ahmed,10093,82,75,68,74,83,57,65,504,A
94,Affan Raza,10095,72,48,99,57,73,76,81,506,A
95,Hasnain Ahmed,10096,62,100,85,54,96,94,83,574,A
98,Nabeel Ahmed,10099,97,75,81,98,72,50,85,558,A

In [70]:
df[df['ML'] == df['ML'].max()]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
33,Zubair Ali,10034,77,98,60,42,100,100,62,539,A

In [71]:
df[df['DL'] == df['DL'].min()]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
4,Ali Hamza,10005,82,72,67,50,53,40,54,418,B

In [72]:
df[df['Total'] > df['Total'].mean()]

,name,roll num,python,numpy,pandas,streamlit,ML,DL,NLP,Total,Grade
3,Hassan Raza,10004,87,99,63,64,85,43,94,535,A
5,Usman Tariq,10006,91,88,62,64,80,65,49,499,A
6,Bilal Ahmed,10007,81,90,44,53,96,88,87,539,A
8,Abdul Rehman,10009,93,58,51,92,62,93,66,515,A
9,Zain Ali,10010,71,100,71,93,73,88,85,581,A
11,Saad Ahmed,10012,75,100,99,48,80,60,76,538,A
12,Umer Farooq,10013,47,89,98,42,48,85,95,504,A
14,Hamza Ali,10015,45,73,45,95,67,75,95,495,A
16,Noman Ahmed,10017,81,62,94,84,54,84,67,526,A
17,Shahzaib Ali,10018,90,54,96,88,81,96,98,603,A
18,Danish Raza,10019,80,41,92,77,93,52,85,520,A
21,Mubashir Ali,10022,89,56,61,86,60,87,89,528,A
22,Taha Raza,10023,42,56,88,63,95,76,75,495,A
24,Shoaib Malik,10025,72,82,72,68,98,55,73,520,A
25,Rizwan Ali,10026,66,48,99,74,81,81,97,546,A
29,Sameer Ahmed,10030,91,75,82,72,56,67,91,534,A
30,Haris Ali,10031,54,95,79,85,78,60,98,549,A
31,Yasir Raza,10032,56,75,96,52,76,99,79,533,A
32,Junaid Ahmed,10033,80,73,76,95,83,93,43,543,A
33,Zubair Ali,10034,77,98,60,42,100,100,62,539,A
34,Irfan Ahmed,10035,94,66,85,87,64,65,76,537,A
35,Kashif Raza,10036,80,65,48,83,82,91,69,518,A
38,Moiz Raza,10039,42,81,77,69,97,79,92,537,A
40,Anas Ahmed,10041,60,69,90,66,93,85,79,542,A
41,Rayan Raza,10042,67,94,82,46,49,64,95,497,A
43,Farhan Ahmed,10044,94,87,43,62,50,94,71,501,A
44,Ubaid Raza,10045,83,56,69,83,67,48,89,495,A
47,Zeeshan Raza,10048,41,74,87,60,91,96,61,510,A
48,Rehan Ali,10049,42,87,48,76,86,74,83,496,A
51,Zahid Ali,10052,78,44,60,93,98,61,73,507,A
52,Qasim Ahmed,10053,95,60,44,70,97,93,76,535,A
53,Muneeb Raza,10054,97,93,83,46,60,65,68,512,A
55,Areeb Ahmed,10056,75,93,80,63,58,70,87,526,A
63,Ibrahim Ali,10064,91,58,56,100,98,49,93,545,A
66,Sufyan Ali,10067,74,83,72,67,66,99,56,517,A
71,Rafay Raza,10072,90,43,97,50,88,81,75,524,A
72,Ehsan Ali,10073,83,77,47,80,71,79,77,514,A
74,Zarar Raza,10075,87,48,66,88,74,98,44,505,A
76,Ismail Ahmed,10077,79,85,84,97,78,92,62,577,A
77,Ahsan Raza,10078,43,88,91,78,62,81,62,505,A
78,Zain Ul Abidin,10079,56,61,71,90,65,66,92,501,A
80,Rizwan Ahmed,10081,85,40,74,96,84,93,40,512,A
81,Shakir Raza,10082,99,95,77,47,84,98,58,558,A
82,Faisal Ali,10083,53,77,99,42,77,84,64,496,A
83,Amin Ahmed,10084,100,95,92,85,89,87,48,596,A
89,Haseeb Ahmed,10090,56,71,63,88,59,78,99,514,A
90,Mahad Ali,10091,44,80,62,53,83,76,97,495,A
91,Rohail Raza,10092,83,78,70,65,70,65,82,513,A
92,Shahbaz Ahmed,10093,82,75,68,74,83,57,65,504,A
94,Affan Raza,10095,72,48,99,57,73,76,81,506,A
95,Hasnain Ahmed,10096,62,100,85,54,96,94,83,574,A
98,Nabeel Ahmed,10099,97,75,81,98,72,50,85,558,A